name: Test
on: [push, pull_request]
jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
        env:
          PSI_KEY: { { secrets.PSI_KEY } }
      - name: Install dependencies
        run: npm install && export PSI_KEY=${{ secrets.PSI_KEY }}
      - name: Run tests
        run: npm run test
      - name: Run coverage
        run: npm run coverage
      - name: Upload coverage to Codacy
        run: export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }} && bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/*
        continue-on-error: true
